# Generated by Django 2.0.2 on 2018-03-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20180302_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_cat',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article_cat',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
