# Generated by Django 2.0.2 on 2018-03-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20180302_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='conect_us',
        ),
        migrations.RemoveField(
            model_name='config',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='config',
            name='keyword',
        ),
        migrations.AddField(
            model_name='config',
            name='connect_us',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='about_us',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
