# Generated by Django 2.0.2 on 2018-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20180304_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_cat',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
