# Generated by Django 2.0.2 on 2018-03-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_article_cat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_cat',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='article_cat',
            name='update_time',
        ),
    ]
