# Generated by Django 2.0.2 on 2018-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_auto_20180306_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
