# Generated by Django 2.0.2 on 2018-03-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_auto_20180307_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='me_name',
            new_name='my_name',
        ),
    ]
